// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: feeds_and_users.sql

package database

import (
	"context"
)

const listFeedsWithUsers = `-- name: ListFeedsWithUsers :many
select
	f.name as feed_name,
	f.url as url,
	u.name as user_name
	from feeds as f
join users as u on u.id = f.user_id
order by f.created_at desc
`

type ListFeedsWithUsersRow struct {
	FeedName string
	Url      string
	UserName string
}

func (q *Queries) ListFeedsWithUsers(ctx context.Context) ([]ListFeedsWithUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listFeedsWithUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeedsWithUsersRow
	for rows.Next() {
		var i ListFeedsWithUsersRow
		if err := rows.Scan(&i.FeedName, &i.Url, &i.UserName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
