// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: unfollow_by_user.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const unfollowFeedByUserAndUrl = `-- name: UnfollowFeedByUserAndUrl :one
delete from feed_follows as ff
using feeds as f
where ff.feed_id = f.id
	and ff.user_id = $1
	and f.url = $2
returning ff.id
`

type UnfollowFeedByUserAndUrlParams struct {
	UserID uuid.UUID
	Url    string
}

func (q *Queries) UnfollowFeedByUserAndUrl(ctx context.Context, arg UnfollowFeedByUserAndUrlParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, unfollowFeedByUserAndUrl, arg.UserID, arg.Url)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
